### ISSUE TITLE
Client model relations

### ISSUE THREAD

**Issue by karelvasicek** [farmani/yii2-dev-test#2]
Please fix and consolidate.

**Comment by farmani** [comment]
@karelvasicek oops sorry I forgot to change it to seller_id

**Comment by karelvasicek** [comment]
Why are some relations declared in `models/base/Client.php` and some in `models/Client.php`?

**Comment by farmani** [comment]
@karelvasicek base classes have been generated by gii and I use this pattern in all my yii projects when I change a table I can simply create a new model by gii and it will replace in base class but my business logic code is in child class in models folder. in here for those relations I define two new method because of the name gii choose for them. their name was not so clear but I write two methods with better name to understand by developers

**Comment by karelvasicek** [comment]
Model is bloated a little bit but the logic sounds good. Thanks.
